name: Test HighReach Download

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      VIDEO_URL: "https://youtube.com/shorts/P3WwWuEa7BQ"

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install requests

      - name: Get Direct URL
        id: geturl
        env:
          VIDEO_URL: ${{ env.VIDEO_URL }}
        run: |
          python << 'EOF'
          import os
          import requests

          def resolve_redirects(url):
              current = url

              for _ in range(15):
                  r = requests.get(
                      current,
                      allow_redirects=False,
                      timeout=30
                  )

                  if 300 <= r.status_code < 400:
                      nxt = r.headers.get("Location")
                      if not nxt:
                          break
                      current = nxt
                  else:
                      break

              return current

          api_url = "https://highreach.ai/api/tools/twitter-gif-download"

          r = requests.post(
              api_url,
              json={"tweet_url": os.environ["VIDEO_URL"]},
              headers={
                  "accept": "*/*",
                  "Referer": "https://highreach.ai/tools/youtube-video-downloader"
              },
              timeout=60
          )

          r.raise_for_status()

          data = r.json()
          formats = data.get("formats", [])

          priorities = [
              "mp4 (1080p60)",
              "mp4 (720p60)",
              "mp4 (480p)",
              "mp4 (360p)"
          ]

          selected = None

          for q in priorities:
              selected = next(
                  (f for f in formats if f.get("quality") == q),
                  None
              )

              if selected:
                  break

          if not selected:
              raise Exception("No format found")

          final_url = resolve_redirects(selected["url"])

          print("FINAL URL:")
          print(final_url)

          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
              f.write(f"direct_url={final_url}\n")
          EOF


      - name: Download with ffmpeg
        run: |
          ffmpeg \
            -user_agent "Mozilla/5.0" \
            -i "${{ steps.geturl.outputs.direct_url }}" \
            -c copy \
            input_video.mp4
